### ISSUE TITLE
Issue with TypoScript generation in TYPO3 8.4

### ISSUE THREAD

**Issue by fnagel** [fnagel/beautyofcode#13]
When adding a new BoC plugin C, the following error is thrown :

`An error occurred trying to process items for field "Programming Language" (Path does not exist in array).`

The language select is empty at this point. Saving (and therefor reloading) the form fixes this.

This is not the case in TYPO3 7.6.

**Comment by NeoBlack** [comment]
this happens only if the TypoScript is not added to the page.
After include the static template, the message is gone.
So my thought was, I missed the template, added it and it worked ;) imho no bug, but is is your extension :D

**Comment by fnagel** [comment]
Mhh, ok. Yesterday I only updated an existing 8.3 with already installed BoC and experienced this issue. 

I need to check this again. Thanks for your feedback!

**Comment by thomaskieslich** [comment]
it happens if you not add TS to root template.

**Comment by fnagel** [comment]
> it happens if you add TS to templates on Subpages not on root.

You're right. I'm able to confirm this issue and it's not a problem in TYPO3 7.6. So this seems TYPO3 8.x related. 
Not sure what to do about this. It might have something to do with how the TS is fetched. Related commit: https://github.com/fnagel/beautyofcode/commit/72874875238a3fafc4942eb4d50ef7cf7cce2814

I will add some note in the documentation for now.

**Comment by michadu** [comment]
It happens also if you have more than one root page and the page with the plugin is not on the tree of the first root page.

**Comment by fnagel** [comment]
@michadu Just tried to reproduce this in TYPO3 8.7 and was not able to reproduce this issue. Did you use `module.tx_beautyofcode < plugin.tx_beautyofcode` after changing the default TS?

**Comment by fnagel** [comment]
@thomaskieslich @all Quick question: do you think it would be a nice feature to have proper TS fetching in BE when overwriting the TS on sub pages (so no more limitation to root templates)? I think that would be possible with some changes to the SettingsService.

**Comment by fnagel** [comment]
I've did some changes to the `SettingsService` in https://github.com/fnagel/beautyofcode/commit/60d73f3e4be024e7ff175f270460fa0cae7fca34

Would you mind to test those?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by michadu** [comment]
I have checked out commit 60d73f3e4be024e7ff175f270460fa0cae7fca34 and it does not solve my problem.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
