### ISSUE TITLE
t3editor in News Contenelement 

### ISSUE THREAD

**Issue by thomaskieslich** [fnagel/beautyofcode#16]
If i use beautyofcode as Contentelement for News then the code area has LineNumbers and no content. I think it is not a Problem from this Ext ;-) 
I can work with t3editor if i set:
$GLOBALS['TCA']['tx_news_domain_model_news']['columns']['content_elements']['config']['appearance']['collapseAll'] = 0;
With many CE Items not a Solution or i can disable t3editor with the Pull request.

**Comment by fnagel** [comment]
Yeah, this is an issue I noticed before. It'S related to the t3editor extension and I'm not sure what to do about it. We had some JS based workarounds for that (afair), but not those never really worked reliable. 
I'm open for suggestions how to fix this!

Please note it's possible to disable the t3editor support in EM (see `enable_t3editor `).

**Comment by fnagel** [comment]
Missed your PR (#15), but I will take a look now...

**Comment by fnagel** [comment]
PR is merged into master. TER version will be releases soon!

**Comment by fnagel** [comment]
Might be related to https://forge.typo3.org/issues/73425 but this should be merged long time ago...

**Comment by thomaskieslich** [comment]
Thanks for merging. 
73425 is merged to 7.6 
https://forge.typo3.org/projects/typo3cms-core/repository/revisions/e9f2bfae9fa210622791f0600bf420ec01b29cac
Perhaps it is lost in 8.x

**Comment by fnagel** [comment]
Which TYPO3 version you are using?

Anyway, seems to be integrated to both, 7.6 and 8.x branch:
https://github.com/TYPO3/TYPO3.CMS/commit/94e822fc46c4bab313a492071bfce58bfcca4903
https://github.com/TYPO3/TYPO3.CMS/commit/e9f2bfae9fa210622791f0600bf420ec01b29cac
