### ISSUE TITLE
Compatibility with PHP 7.1 

### ISSUE THREAD

**Issue by psychomieze** [fnagel/beautyofcode#18]
At the moment the composer.json states beautyofcode is only compatible with PHP < 7.1 - I've got it running with PHP 7.1 for quite some time and am wondering - are there specific issues?

**Comment by fnagel** [comment]
No, I was not able to test it yet and had no feedback until now. I will push a fix asap. Thanks for reporting!

Are you using TYPO3 8.7 (asking because of #17)?
