### ISSUE TITLE
Additional text area for URLs and reference files

### ISSUE THREAD

**Issue by luisafassbender** [fnagel/beautyofcode#20]
We added an additional area, where editors can insert a URL or a file reference: The content of the chosen URL or file reference will then be displayed in the FE. 

However the following logic has been implemented: Code > file reference / URL. So if an editor added a file reference in the first step and code in a second step, the code will be displayed in the FE.

**Comment by fnagel** [comment]
@luisafassbender @sfsmfc @michadu 

Finally implemented this change. Some more improvements too. Feedback would be appreciated!

See here: https://github.com/fnagel/beautyofcode/tree/typo3-9

**Comment by sfsmfc** [comment]
Looks good for me. Thanks!

**Comment by fnagel** [comment]
Released in version 4.0.0.
