### ISSUE TITLE
Flexform configuration settings do not arrive on frontend properly

### ISSUE THREAD

**Issue by BastianBalthasarBux** [fnagel/beautyofcode#24]
Flexform configuration settings do not arrive on frontend properly (check f:debug {flexform} ...)
Therefore no highlighting.
Furthermore due to "language-undefined" prism breaks completely if used.
Same problem btw on your own page which is linked as an example.

Version: 3.3.0 and 3.2.0 tested, occurs with both.
TYPO3: 8.7.24

**Comment by fnagel** [comment]
This seems like #17 is not really solved :-/

I will reopen #17 and close this ticket. Please resume discussion there...
